### ISSUE TITLE
Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen

### ISSUE THREAD

**Issue by ThomasLoeffel** [HM-RedMatic/RedMatic#160]
Hallo hobbyquarker,

in meinem Projekt möchte ich Amazon "Polly" auf einem Sonos Lautsprecher in Echtzeit ausgeben.
Hierfür gibt es auch eine "Node-Red-contrib-sonospollytts". Ein Video habe ich auch dazu gefunden. Ich habe alles auch genau so gemacht.
https://www.youtube.com/watch?v=piq-sdvL6RU

Allerdings funktioniert die "note" auf Redmatic nicht richtig. 

Der Sonos reagiert bei jedem Deploy auf die "Laustärkeänderungen" (wenn ich z.B. Radio anhabe). Aber kein Text wird gesprochen und auch nicht der Start Ton abgespielt. Weiterhin habe ich einmal auf einem Raspberry IOBROKKER installiert und dort dann Node-Red. Hier klappt es genau wie beschrieben.

Ggf. ist der Port falsch (1880, oder auch 80) geht nicht. Die Node sagt das Node.js min 8.9... sein soll. Leider sagt mir das nichts.

Gruß Thomas

**Comment by hobbyquaker** [comment]
Crosspost: https://homematic-forum.de/forum/viewtopic.php?f=77&t=49480

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,
hattest Du wie angekündigt Zeit am Wochenende dieses Thema anzusehen?
Auch mit dem neuen Update von Redmatic geht dieses leider nicht.

Gruß Thomas

**Comment by hobbyquaker** [comment]
Ich vermute das Problem liegt hier: https://github.com/Supergiovane/node-red-contrib-sonospollytts/blob/master/sonospollytts/sonospollytts.js#L464
Änder mal diese Zeile ab in
`sNoderedURL="http://"+ config.noderedipaddress + ":" + config.noderedport + RED.settings.httpRoot;` (Datei ist hier zu finden: `/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonospollytts/sonospollytts/`) und starte Node-RED neu. Wenn das geht mach ich ein Pull Request dafür.

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

mit Deiner Modifikation geht es. Allerdings muss man Port 80 benutzen!
Folgendes stellt sich komischerweise noch ein:
Fall 1:
IOBROKER mit "sayit" auf Synology über Docker
- Im Falle das ich dort den Flow: node-red-contrib-better-sonos Version: 0.1.21 benutze und
node-red-contrib-sonospollytts Version 1.04.

Das System spielt einen Song und ich benutze dann den Flow IOBROKER input und IOBROKER output. Dann wird der Song unterbrochen, sayit sagt den Text und der Song startet wieder. Spiele ich nun Radio ab, unterbricht sayit das Radio und startet Radio nicht neu. Aber ich kann es über die "better-sonos" wieder normal starten.

- Im Fall ich benutze sonospollytts dann unterbricht er den Song oder wartet bis ich Radio stoppe und spiel dann auch den Text (ohne sayit) ab. Aber ich kann den Song oder das Radio über die "better-sonos" nicht mehr starten. Ich muss von aussen einen Song starten oder "Alexa" bitten Radio wieder abzuspielen. Sehr komisch.

Gruß und Danke Thomas

**Comment by hobbyquaker** [comment]
Hab ein Pull Request aufgemacht, hoffe der wird zeitnah gemerged, dann ist die manuelle Modifikation nicht mehr nötig. Warum das mit dem Unterbrechen/Wiederabspielen nicht geht - kein Ahnung, mangels Sonos Geräten kann ich das auch nicht testen...
Ich würde sagen wir lassen den Issue hier mal offen bis der Fehler in sonospollytts behoben ist.

**Comment by hobbyquaker** [comment]
Das, ging schnell, wurde gemerged. Ich denke wenn es eine neue Version von node-red-contrib-sonospollytts gibt ist das Problem erstmal gelöst. Dass Du Port 80 nutzen musst ist übrigens normal, das liegt daran dass Node-RED hinter dem Webserver der CCU "verborgen" wird. Es lauscht zwar selbst noch auf Port 1880, ist aber von außen nicht über diesen Port erreichbar.

**Comment by Supergiovane** [comment]
Thank you hobbyquacker. The new versione will ne publicherete ad sono ad possibile.

**Comment by schuwo** [comment]
Hallo !
SonospollyTTS funktioniert bei mir auf Anhieb (und auf Port 80) perfekt, aber:
Hat irgendwer eine Idee, wie ich die Durchsage auf 3 Sonos 1 gleichzeitig - oder auch kurz nacheinander laufen lassen kann. Ich hab alle Möglichkeiten ausprobiert, die Durchsage kommt aber immer nur auf einem Gerät

**Comment by Supergiovane** [comment]
Schuwo, i don't speak German. The node is meant to be used on only 1 sonos player. Currently is not possible to use more than 1 sonos player. We'll working for an update in the near future, allowing you to do what i think you want.

**Comment by schuwo** [comment]
Hello Supergiovane !

Thanks for Your immediate answer. Your node is excellent and i´m looking forward  Your updates ! ( I want to connect my SONOS players to the doorbell but we have to hear it in all rooms ).

Really great node ! An excuse my bad English 

Wolfgang

 

 

 

Von: Supergiovane [mailto:notifications@github.com] 
Gesendet: Montag, 15. April 2019 09:30
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: schuwo <wolfgang@schur.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)

 

Schuwo, i don't speak German. The node is meant to be used on only 1 sonos player. Currently is not possible to use more than 1 sonos player. We'll working for an update in the near future, allowing you to do what i think you want.

**Comment by Supergiovane** [comment]
Hello
to do this, you simply need to group the players. You can do it in the sonos app.

Il giorno 15 apr 2019, alle ore 10:08, schuwo <notifications@github.com> ha scritto:

Hello Supergiovane !

Thanks for Your immediate answer. Your node is excellent and i´m looking forward Your updates ! ( I want to connect my SONOS players to the doorbell but we have to hear it in all rooms ).

Really great node ! An excuse my bad English 

Wolfgang







Von: Supergiovane [mailto:notifications@github.com] 
Gesendet: Montag, 15. April 2019 09:30
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: schuwo <wolfgang@schur.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)



Schuwo, i don't speak German. The node is meant to be used on only 1 sonos player. Currently is not possible to use more than 1 sonos player. We'll working for an update in the near future, allowing you to do what i think you want.

**Comment by schuwo** [comment]
Hello !

I cannot group my Sonos players for all time. Because if I write in my room I like to hear music ( or radio – becouse we have bad receiving „on the air“) and my wife -  ironing or reading in another room hates to hear music or radio for all the time ). I´m shure you find a possibility to group the players in the moment the TTS is coming in from AWS pollyTTS……….?

Buon giorno  e con la più grande ammirazione e grazie di cuore

Wolfgang

 

 

 

Von: Supergiovane [mailto:notifications@github.com] 
Gesendet: Montag, 15. April 2019 10:33
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: schuwo <wolfgang@schur.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)

 

Hello
to do this, you simply need to group the players. You can do it in the sonos app.

Il giorno 15 apr 2019, alle ore 10:08, schuwo <notifications@github.com> ha scritto:

Hello Supergiovane !

Thanks for Your immediate answer. Your node is excellent and i´m looking forward Your updates ! ( I want to connect my SONOS players to the doorbell but we have to hear it in all rooms ).

Really great node ! An excuse my bad English 

Wolfgang







Von: Supergiovane [mailto:notifications@github.com] 
Gesendet: Montag, 15. April 2019 09:30
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: schuwo <wolfgang@schur.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)



Schuwo, i don't speak German. The node is meant to be used on only 1 sonos player. Currently is not possible to use more than 1 sonos player. We'll working for an update in the near future, allowing you to do what i think you want.

**Comment by Supergiovane** [comment]
Hello Wolfgang,
if group the players via sonospollytts, for sure you'll hear a very long delay between players and this is not a fault, it's due to how sonos works. 
Each single player will do an http web call to the sonospollytts to stream the speech audio, but ther's no way to sync all players. 
The only way to play an audo synchronously, is to do a group in the sonos app. Maybe you can buy a player only for the doorbell, and make a group with this player? In this case, the doorbell rings on all players and you wife can still enjoy the silence when you're listening for music with the other players.
I've never done that before, because i've only one sonos AMP, so i cannot currently reproduce your setup.


Il giorno 15 apr 2019, alle ore 11:11, schuwo <notifications@github.com> ha scritto:

Hello !

I cannot group my Sonos players for all time. Because if I write in my room I like to hear music ( or radio – becouse we have bad receiving „on the air“) and my wife - ironing or reading in another room hates to hear music or radio for all the time ). I´m shure you find a possibility to group the players in the moment the TTS is coming in from AWS pollyTTS……….?

Buon giorno e con la più grande ammirazione e grazie di cuore

Wolfgang







Von: Supergiovane [mailto:notifications@github.com] 
Gesendet: Montag, 15. April 2019 10:33
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: schuwo <wolfgang@schur.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)



Hello
to do this, you simply need to group the players. You can do it in the sonos app.

Il giorno 15 apr 2019, alle ore 10:08, schuwo <notifications@github.com> ha scritto:

Hello Supergiovane !

Thanks for Your immediate answer. Your node is excellent and i´m looking forward Your updates ! ( I want to connect my SONOS players to the doorbell but we have to hear it in all rooms ).

Really great node ! An excuse my bad English 

Wolfgang







Von: Supergiovane [mailto:notifications@github.com] 
Gesendet: Montag, 15. April 2019 09:30
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: schuwo <wolfgang@schur.at>; Comment <comment@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)



Schuwo, i don't speak German. The node is meant to be used on only 1 sonos player. Currently is not possible to use more than 1 sonos player. We'll working for an update in the near future, allowing you to do what i think you want.

**Comment by Supergiovane** [comment]
Hello Wolfgang,
Version 1.0.8 is coming out and should fix the multi node issue.

Il giorno 15 apr 2019, alle ore 11:23, Massimo Saccani <massimo@saccani.it> ha scritto:

Hello Wolfgang,
if group the players via sonospollytts, for sure you'll hear a very long delay between players and this is not a fault, it's due to how sonos works. 
Each single player will do an http web call to the sonospollytts to stream the speech audio, but ther's no way to sync all players. 
The only way to play an audo synchronously, is to do a group in the sonos app. Maybe you can buy a player only for the doorbell, and make a group with this player? In this case, the doorbell rings on all players and you wife can still enjoy the silence when you're listening for music with the other players.
I've never done that before, because i've only one sonos AMP, so i cannot currently reproduce your setup.


Il giorno 15 apr 2019, alle ore 11:11, schuwo <notifications@github.com <mailto:notifications@github.com>> ha scritto:

Hello !

I cannot group my Sonos players for all time. Because if I write in my room I like to hear music ( or radio – becouse we have bad receiving „on the air“) and my wife - ironing or reading in another room hates to hear music or radio for all the time ). I´m shure you find a possibility to group the players in the moment the TTS is coming in from AWS pollyTTS……….?

Buon giorno e con la più grande ammirazione e grazie di cuore

Wolfgang







Von: Supergiovane [mailto:notifications@github.com <mailto:notifications@github.com>] 
Gesendet: Montag, 15. April 2019 10:33
An: rdmtc/RedMatic <RedMatic@noreply.github.com <mailto:RedMatic@noreply.github.com>>
Cc: schuwo <wolfgang@schur.at <mailto:wolfgang@schur.at>>; Comment <comment@noreply.github.com <mailto:comment@noreply.github.com>>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)



Hello
to do this, you simply need to group the players. You can do it in the sonos app.

Il giorno 15 apr 2019, alle ore 10:08, schuwo <notifications@github.com <mailto:notifications@github.com>> ha scritto:

Hello Supergiovane !

Thanks for Your immediate answer. Your node is excellent and i´m looking forward Your updates ! ( I want to connect my SONOS players to the doorbell but we have to hear it in all rooms ).

Really great node ! An excuse my bad English 

Wolfgang







Von: Supergiovane [mailto:notifications@github.com <mailto:notifications@github.com>] 
Gesendet: Montag, 15. April 2019 09:30
An: rdmtc/RedMatic <RedMatic@noreply.github.com <mailto:RedMatic@noreply.github.com>>
Cc: schuwo <wolfgang@schur.at <mailto:wolfgang@schur.at>>; Comment <comment@noreply.github.com <mailto:comment@noreply.github.com>>
Betreff: Re: [rdmtc/RedMatic] Die "Node" Sonospollytts bekomme ich auf REDMATIC nicht zum laufen (#160)



Schuwo, i don't speak German. The node is meant to be used on only 1 sonos player. Currently is not possible to use more than 1 sonos player. We'll working for an update in the near future, allowing you to do what i think you want.
